let money = 100;
let powerPlantCount = 0;
let pollutionTax = 0;

// Load game data from local storage if available
const savedGame = JSON.parse(localStorage.getItem('idlePowerPlantGame'));
if (savedGame) {
    money = savedGame.money || 100;
    powerPlantCount = savedGame.powerPlantCount || 0;
    pollutionTax = savedGame.pollutionTax || 0;
} else {
    // If no saved game data exists, initialize with starting money
    money = 100; // Starting money for new players
    saveGame(); // Save the initial game state
}

function buildPowerPlant() {
    const powerPlantCost = 100; // Cost of building a power plant in ISK

    if (money >= powerPlantCost || money === 100) {
        money -= powerPlantCost;
        powerPlantCount++;
        // Increase pollution tax effect with each power plant
        pollutionTax += 5; // Example increase, adjust as needed
        updateDisplay();
        saveGame();
    } else {
        alert("Ógildir fjármagn til að byggja kraftverk!"); // Changed error message to Icelandic
    }
}

function upgradeTaxReduction() {
    const upgradeCost = 50; // Cost of upgrading to reduce pollution tax in ISK
    const taxReductionPercentage = 5; // Percentage of pollution tax reduction per upgrade

    if (money >= upgradeCost) {
        money -= upgradeCost;
        pollutionTax -= taxReductionPercentage; // Reduce pollution tax
        updateDisplay();
        saveGame();
    } else {
        alert("Ógildir fjármagn til að uppfæra skatt!") // Changed error message to Icelandic
    }
}

function updateDisplay() {
    document.getElementById('moneyAmount').textContent = money + ' ISK';
    document.getElementById('powerPlantCount').textContent = powerPlantCount;
    document.getElementById('pollutionTaxAmount').textContent = pollutionTax + '%';
}

function collectIncome() {
    const powerPlantIncome = 10; // Income generated by each power plant

    // Calculate pollution tax reduction from income
    const pollutionTaxReduction = (powerPlantIncome * powerPlantCount) * (pollutionTax / 100);
    
    money += (powerPlantCount * powerPlantIncome) - pollutionTaxReduction;
    updateDisplay();
    saveGame();
}

function saveGame() {
    const gameData = {
        money: money,
        powerPlantCount: powerPlantCount,
        pollutionTax: pollutionTax
    };
    localStorage.setItem('idlePowerPlantGame', JSON.stringify(gameData));
}

// Initialize the game loop to collect income every second
setInterval(collectIncome, 1000);
